language: cpp
sudo: required
dist: trusty

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - clang-3.6
      - autoconf-archive
      - valgrind

env:
  - CFLAGS="-g"

before_install:
  - echo $LANG
  - echo $LC_ALL

install:
  - sh autogen.sh

before_script:
  - # note: valgrind is only available on Linux
  - if [ "$CC" == "gcc" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then export ENA_VG="--enable-valgrind"; fi
  - ./configure $ENA_VG

script:
  - if [ "$CC" == "clang" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then  scan-build-3.6 --status-bugs make check TESTS="" && make clean ; fi
  - make
  - export VERBOSE=1
  - make check
  - make distcheck
